name: SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    name: SonarCloud Scan (Maven)
    runs-on: ubuntu-latest
    if: secrets.SONAR_TOKEN != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run SonarCloud scanner (Maven)
        env:
          SONAR_TOKEN: ${{ c9f06d2814c611794dbb375467113b41ce74c3a9 }}
        working-directory: qa/backend
        run: |
          chmod +x ./mvnw.cmd || true
          ./mvnw.cmd -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=${{ EmashaChathuni_qa-project-demo }} \
            -Dsonar.organization=${{ EmashaChathuni }} \
            -Dsonar.host.url=${{ https://sonarcloud.io }}

# Notes:
# - This workflow runs only if SONAR_TOKEN is set in repository secrets.
# - Required secrets: SONAR_TOKEN, SONAR_PROJECT_KEY, SONAR_ORGANIZATION, SONAR_HOST_URL (e.g., https://sonarcloud.io)name: REMOVED - SonarCloud workflow was removed

# This workflow was removed on 2025-10-12. To re-enable SonarCloud, recreate the workflow
# and set the required repository secret: SONAR_TOKEN

